### ISSUE TITLE
Property 'intercept' in type 'ApmInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>

### ISSUE THREAD

**Issue by purplefish32** [xiz0r/nestjs-apm#1]
Hello, 
I tried installing your module, but I get the following error :
```
node_modules/nestjs-apm/dist/apm.interceptor.d.ts(7,5): error TS2416: Property 'intercept' in type 'ApmInterceptor' is not assignable to the same property in base type 'NestInterceptor<any, any>'.
  Type '(context: ExecutionContext, call$: Observable<any>) => Observable<any>' is not assignable to type '(context: ExecutionContext, next: CallHandler<any>) => Observable<any> | Promise<Observable<any>>'.
    Types of parameters 'call$' and 'next' are incompatible.
      Type 'CallHandler<any>' is missing the following properties from type 'Observable<any>': _isScalar, source, operator, lift, and 6 more.
```

**Comment by enissay-git** [comment]
I thinks it related to the new way to create NestInterceptor : 
// Before
@Injectable()
export class TransformInterceptor implements NestInterceptor {
  intercept(
    context: ExecutionContext,
    call$: Observable<T>,
  ): Observable<Response<T>> {
    return call$.pipe(map(data => ({ data })));
  }
}

// After
@Injectable()
export class TransformInterceptor implements NestInterceptor {
  intercept(
    context: ExecutionContext,
    next: CallHandler,
  ): Observable<Response<T>> {
    return next
      .handle()
      .pipe(map(data => ({ data })));
  }
}

https://docs.nestjs.com/migration-guide#interceptors

**Comment by enissay-git** [comment]
Hello @xiz0r i have made a PR if it's good for you you can merge it and republish, but i can improve it if needed : https://github.com/xiz0r/nestjs-apm/pull/3

**Comment by enissay-git** [comment]
Hello @purplefish32 i have made a quick fix on my side for now (until @xiz0r fix it) you can found it here : https://www.npmjs.com/package/nestjs-apm-v6

**Comment by xiz0r** [comment]
Thanks @enissay-git for the PR, it's already merged and published.
@purplefish32 please update to version 1.0.9.

**Comment by mohamedmonirshabana** [comment]
I have the same Error on class inside Function
